[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-check-permissions",
    "allow-request-permissions",
    "allow-register-listener",
    "allow-registerListener",
    "allow-remove-listener",
    "allow-removeListener",
    "allow-send-sms",
    "allow-get-state",
    "allow-invoke-action"
]
